server:
  port: 8080
spring:
  jpa:
    database-platform: com.example.api_scotia.configuration.dialect.SQLiteDialect
    hibernate:
      show-sql: true
      format_sql: true
      ddl-auto: update
  datasource:
    url: jdbc:sqlite:db_api_scotia.sqlite
    driver-class-name: org.sqlite.JDBC
