# ===================================================================
# GENERAL PROPERTIES
# ===================================================================
server:
  port: 8080
spring:
  jpa:
    hibernate:
      show-sql: true
      format_sql: true
      ddl-auto: validate
      database-platform: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://localhost:3306/db_rapimoney?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  mail:
    host: smtp.gmail.com
    port: 587
    username: rapimoneytest@gmail.com
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  web:
    resources:
      static-locations: classpath:/static/
flyway:
  enabled: true
  locations: classpath:/db/migration
  baseline-on-migrate: true
  baseline-version: 0
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

# ===================================================================
# SECURITY PROPERTIES
# ===================================================================
security:
  jwt:
    key: 08af2447a30c9c090b3595e6b45cead32eb587dcb1892aae31f073dcb31bce95
    lifeTime: 10000
    user:
      generator: RAPI-MONEY

# ===================================================================
# LOG PROPERTIES
# ===================================================================
logging:
  level:
    root: INFO
    com.tu.paquete: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: '[%X{data}%thread] [%X{X-B3-TraceId:-}] - %5p'